# Generated by Django 5.0.6 on 2024-07-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
