# Generated by Django 5.0.6 on 2024-07-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0002_turno_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='servicio',
        ),
        migrations.AddField(
            model_name='turno',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
